import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "300", "400", "500", "600"],
});

export const metadata = {
  title: "Qspiders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full antialiased font-sans",
          poppins.className
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
